tobook_homepage:
    path:     /{_locale}
    defaults: { _controller: TobookBundle:Default:index }

tobook_search:
    path:     /search
    defaults: { _controller: TobookBundle:Default:search }

tobook_clubhouse:
    path:     /clubhouse
    defaults: { _controller: TobookBundle:Default:clubhouse }

changeLocale:
    path:     /{_locale}/change
    defaults: { _controller: TobookBundle:Default:changeLocale}

