tobook_homepage:
    path:     /
    defaults: { _controller: TobookBundle:Default:index }

tobook_search:
    path:     /search
    defaults: { _controller: TobookBundle:Default:search }

changeLocale:
    path:     /change
    defaults: { _controller: TobookBundle:Default:changeLocale}

