wcs_emailing_homepage:
    path:     /emailing/
    defaults: { _controller: WCSEmailingBundle:Default:index }

wcs_emailing_import:
    path:     /emailing/import/{profCode}
    defaults: { _controller: WCSEmailingBundle:Default:importCSV }
    options:
        expose: true

send_mail:
    path:     /emailing/send
    defaults: { _controller: WCSEmailingBundle:Default:sendmail }

wcs_emailing_suppr:
    path:     /emailing/suppr/{idClient}
    defaults: { _controller: WCSEmailingBundle:Default:suppr }
    options:
        expose: true