wcs_emailing_homepage:
    path:     /{_locale}/emailing/
    defaults: { _controller: WCSEmailingBundle:Default:index }

wcs_emailing_import:
    path:     /{_locale}/emailing/import
    defaults: { _controller: WCSEmailingBundle:Default:importCSV }

# wcs_emailing_upload:
#     path:     /{_locale}/emailing/newupload
#     defaults: { _controller: WCSEmailingBundle:Default:uploadCSV }

# wcs_emailing_import:
#     path:     /{_locale}/emailing/import
#     defaults: { _controller: WCSEmailingBundle:Default:importCSV }