club-house:
    path:     /{_locale}/clubhouse/{profCode}
    defaults: {_controller: WCSPropertyBundle:Default:clubhouse }

putFavorites:
    path:     /{_locale}/clubhouse/{profCode}/favorites
    defaults: {_controller: WCSPropertyBundle:Default:favoris }

mapResult:
    path:     /zmapResult
    defaults: {_controller: WCSPropertyBundle:ShowMap:ShowMap }
    options:
        expose: true