club-house:
    path:     /clubhouse/{profCode}
    defaults: {_controller: WCSPropertyBundle:Default:clubhouse }

favorites:
    path:     /clubhouse/{profCode}/favorites
    defaults: {_controller: WCSPropertyBundle:Default:favoris }