tobook:
    resource: "@TobookBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

wcssms:
    resource: "@WCSSMSBundle/Resources/config/routing.yml"
    prefix:   /

wcs_rating:
    resource: "@WCSRatingBundle/Resources/config/routing.yml"
    prefix:   /

user_bundle:
    resource: "@WCSRatingBundle/Resources/config/routing.yml"
    prefix:   /

wcs_property:
    resource: "@WCSPropertyBundle/Resources/config/routing.yml"
    prefix:   /

wcs_content:
    resource: "@WCSContentBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"